$(document).ready(function() {
  // pokemonPopulate()
  fetchDotaHeroes()
  $('.navbar').hide()
  $('#home-page').hide()
  $('#register').hide()
  $('#login').hide()
  $('#pokemon').hide()
  // showRegister()
  // login()
  // submitRegister()
  // loginUser()
})
